[package]
name = "merge-minecraft-litematica-csvs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
eyre = "0.6.5"
serde = { version = "1.0.127", features = ["derive"] }
